### ISSUE TITLE
Improve TechFellows logo in Dark Mode

### ISSUE THREAD

**Issue by mohamedsgap** [techfellows/website#22]
Now, if we switch between **dark** and **light** mode, the logo doesn't look perfect! any idea to make it better! we are open to accept any suggesttion, so feel free to fill a PR that is gonna solve this. Happy Hacktoberfest :+1: 

How the logo looks right now: 
![Screenshot from 2020-10-06 22-03-52](https://user-images.githubusercontent.com/30293804/95257046-058e7880-0824-11eb-8e4b-70a2d85e6a22.png)

![Screenshot from 2020-10-06 22-04-13](https://user-images.githubusercontent.com/30293804/95257053-09ba9600-0824-11eb-803d-40193ce22fd4.png)

**Comment by elenayc** [comment]
I'm interested in this issue.

**Comment by Toshiuk** [comment]
What  do you think about invert the colors? 
![image](https://user-images.githubusercontent.com/8109770/95266252-b6981180-082a-11eb-85c4-ceda700a6b92.png)
