### ISSUE TITLE
Mobile layout in About screen

### ISSUE THREAD

**Issue by DanieIStewart** [techfellows/website#24]
Issue when mobile view the dev cards stack side by side not very nice on the eyes.  If you have a better implantation please add for review.

-about,js
-Mobile view Layout fix

All pull requests will be reviewed. 
![Capture](https://user-images.githubusercontent.com/42270375/95395436-8453e600-08f6-11eb-968e-8c490870b7e5.PNG)

**Comment by Jp1200** [comment]
assign me to this, I can work on it.

**Comment by bklynate** [comment]
I am pushing a PR up now
